### ISSUE TITLE
changes to support devices that send more than 24 bits

### ISSUE THREAD

**Issue by thedinuka** [ninjablocks/arduino#2]
MAX_BUFFER_SIZE should be increased to about 136

**Comment by mylifeofagony** [comment]
Hello Dinuka,

Thanks for the info what should be changed. I was a little busy lately and didn't have time to work on the project. But I think I will manage tonight and commit the changes, so you can work with the updated code...

Have a nice one,
meik

Am 17.03.2013 um 01:39 schrieb Dinuka notifications@github.com:
